### ISSUE TITLE
Spurious line

### ISSUE THREAD

**Issue by bzg** [whamtet/launchpoint#1]
https://github.com/whamtet/launchpoint/blob/4c7f3a84c1152129638063828188926599651a89/src/clj/simpleui/launchpoint/web/views/login.clj#L10 needs to be deleted IMHO.

**Comment by whamtet** [comment]
Thanks for looking over the source Bastien, in https://github.com/whamtet/launchpoint/blob/main/autogen/process.cljs we scan files for all the css classes use and spit them into html for consumption by tailwind.   Tailwind is a thin wrapper around css but it only generates classes used in the source code.  Since it doesn't understand Clojure we spit out html containing the required classes.  In some cases the classes are created in a conditional and the parser is not sophisticated enough to read them, that's why they are standalone at the top of the function.

I've created a noop macro to wrap those statements in, that will make it clearer that they are in fact used.

**Comment by bzg** [comment]
Thanks a lot for the detailed explanations, appreciated!
